# Generated by Django 2.2.5 on 2020-03-28 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptwo', '0003_friend'),
    ]

    operations = [
        migrations.DeleteModel(
            name='friend',
        ),
    ]
